" BEGIN TABS
map \ta :tabnew<cr>
map \tn :tabnext<cr>
map \tm :tabmove
map \tc :tabclose<cr>
map \to :tabonly<cr>
map \tp :tabprevious<cr>
" END TABS
" BEGIN buffers
map ta :enew<cr>
map tn :bnext<cr>
map tp :bprevious<cr>
map tc :bdelete<cr>
" END buffers
